server:
  port: 9988
  ssl: # ssl相关配置
    enabled: true
    key-store: classpath:yaaaa.top.jks
    key-store-password: 4bw9100m9wso3
    key-store-type: JKS
xiaoshen:
  host: localhost
  port: 7788
  token: 666
spring:
  http:
    encoding:
      charset: UTF-8
  redis:
    host: localhost
    database: 0
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/seven?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      use-ping-method: false
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml, classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
logging:
  level:
    top.flagshen.myqq: INFO